plugins {
    id 'java'
    id 'application'
}

application {
    mainClass.set('dev.wonyoung.Application')
}

run {
    standardInput = System.in
    standardOutput = System.out
    errorOutput = System.err
}

group = 'dev.wonyoung'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    // ByteBuddy
    implementation 'net.bytebuddy:byte-buddy:1.14.18'

    // Logging
    implementation 'org.slf4j:slf4j-api:2.0.13'
    implementation 'ch.qos.logback:logback-classic:1.5.6'

    // 테스트
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
